### ISSUE TITLE
Chromely Owin - error running Owin on Chromely CefSharp

### ISSUE THREAD

**Issue by mattkol** [amaitland/Chromium.AspNetCore.Bridge#3]
@amaitland 

Thanks for inviting me to the project. I have been looking at OWIN for a while now but I was reluctant using a "live" host. This approach is what Chromely needs as an actual web "live" hosting process is not required.

I have been able to [integrate it into Chromely](https://github.com/mattkol/CefSharp.AspNetCore.Mvc/tree/master/ChromelyOwin).

There will be 2 main ChromelyApp classes:
1. [ChromelyOwinAppBase](https://github.com/mattkol/CefSharp.AspNetCore.Mvc/blob/master/ChromelyOwin/Chromely/ChromelyOwinAppBase.cs) - Using Owin
2. [ChromelyBasicApp](https://github.com/mattkol/CefSharp.AspNetCore.Mvc/blob/master/ChromelyOwin/Chromely/ChromelyBasicApp.cs) - The second will fall back to the current way.

There are 5 demo projects:

1. ChromelyCefGlueOwinDemo - CefGlue Owin app 
2. ChromelyCefSharpOwinDemo - CefSharp Owin app
3. RazorPagesMovie - CefGlue Owin app (Razor pages)
4. CrossPlatDemo - usual Chromely cross-platform demo
5. CefSharpDemo - usual Chromely CefSharp 

I am not able to run ChromelyCefSharpOwinDemo successfully yet. There is an error. Seems like a threading issue.

![error1](https://user-images.githubusercontent.com/18384207/113510389-a8505700-9528-11eb-975d-82c4d8d6435d.png)
![error2](https://user-images.githubusercontent.com/18384207/113510392-aab2b100-9528-11eb-9630-e4652cc959fe.png)

**Thoughts? Also any feedbacks on implementations will be appreciated.**

Thanks.

**Comment by amaitland** [comment]
> I think I understand what you mean, more like a library of features that is not specific to CefSharp. That should be fine if that is the case.

I actually removed all the `CefSharp` specific code a while ago (was moved into `CefSharp` directly). I've actually just finished the major refactor and decided that I can get away without having specific implementations for `WebView2` and `CefGlue` so the project has been renamed to `Chromium.AspNetCore.Bridge` and the repository is now public.

The `Chromely` and `WebView2` examples have been refactored to use the new [RequestInterceptor](https://github.com/amaitland/Chromium.AspNetCore.Bridge/blob/eaa0e0ae9e7fddf541379dfaaa4bde5fbca6c488/Chromium.AspNetCore.Bridge/RequestInterceptor.cs#L14) class which provides a convenient way to execute the `OWIN` request.
- https://github.com/amaitland/Chromium.AspNetCore.Bridge/blob/master/Chromely.AspNetCore.Mvc.Example/Owin/OwinResourceHandler.cs#L82
- https://github.com/amaitland/Chromium.AspNetCore.Bridge/blob/master/WebView2.AspNetCore.Mvc.Example.Wpf/MainWindow.xaml.cs#L38

> I cannot remember making any changes to [OwinServer](https://github.com/mattkol/CefSharp.AspNetCore.Mvc/blob/master/ChromelyOwin/Chromely.AspNetCore/Owin/OwinServer.cs)
> [OwinFeatureImpl](https://github.com/mattkol/CefSharp.AspNetCore.Mvc/blob/master/ChromelyOwin/Chromely.AspNetCore/Owin/OwinFeatureImpl.cs).

You should be able to use the library without modification. Contributions are welcome and I'd appreciate any feedback on the `API` you have.

Let me know what you think/any questions. I'll release a `Nuget` package after you've had a chance to review.

**Comment by mattkol** [comment]
@amaitland I deleted some of the comments.
Please can you send me an email. My email is listed. Thanks.

**Comment by mattkol** [comment]
@amaitland my advice is that a fresh new issue be created to track as this
is public now. Those previous comments were done privately.
