### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by mattkol** [amaitland/Chromium.AspNetCore.Bridge#5]
@amaitland 

Redirect may need a closer look.
See how I am handling it - 

https://github.com/mattkol/Chromium.AspNetCore.Bridge/blob/e42b3c71431b38ae66a963624157b316017e4da4/WebView2.Mvc.Example.Wpf/OwinResourceHandler.cs#L35

It could be encapsulated in the Chromium.AspNetCore.Bridge or use a different approach.

I created 2 samples:
1. [Wpf Mvc Razor](https://github.com/mattkol/Chromium.AspNetCore.Bridge/tree/master/WebView2.Mvc.Example.Wpf)
2. [Wpf Razor Pages](https://github.com/mattkol/Chromium.AspNetCore.Bridge/tree/master/WebView2.RazorPages.Example.Wpf)

**Comment by amaitland** [comment]
I would have expected a redirect to be handled by the browser, is the http status code being returned correctly?

**Comment by amaitland** [comment]
I vaguely remember reading that WebView2 was dropping the first header from an intercepted response,  maybe try prepend a dummy x-powered-by (or something similar) header? Possibly the location header is being ignored.

**Comment by mattkol** [comment]
> I would have expected a redirect to be handled by the browser, is the http status code being returned correctly?

Yes, the status code is returned correctly (302), the location header is correct too. What I think is Owin is not internally processing it and returning it as response instead. This does not happen with CefSharp or CefGlue because I think that internally CEF redirects. What I am wondering about is if there is an approach out there to make Owin process it and return a final expected redirect response. Or the actual processing is done in Chromium.AspNetCore.Bridge. Or the developer just deals with it.

![image](https://user-images.githubusercontent.com/18384207/117138895-9d802080-ad79-11eb-8078-080e8e8c602b.png)
![image](https://user-images.githubusercontent.com/18384207/117139057-cb656500-ad79-11eb-90c1-f1910ffd6c2d.png)

**Comment by mattkol** [comment]
> I vaguely remember reading that WebView2 was dropping the first header from an intercepted response, maybe try prepend a dummy x-powered-by (or something similar) header? Possibly the location header is being ignored.

Please show an example of this.

**Comment by amaitland** [comment]
> What I think is Owin is not internally processing it and returning it as response instead.

The request shouldn't be processed internally, a response should flow through to the browser and a subsequent request made.

> This does not happen with CefSharp or CefGlue because I think that internally CEF redirects.

That suggests this is a bug in `WebView2`. This is the behaviour I expect.

> What I am wondering about is if there is an approach out there to make Owin process it and return a final expected redirect response.

I don't believe this is the correct approach. Redirects aren't limited to the same origin, the browser should handle them correctly in my opinion.

> Please show an example of this.

Quick check and it didn't work  so doesn't matter. I see the error code is `ERR_INVALID_RESPONSE`, need to double check though I don't think we need more than a 30x status code and a `Location` header. So for me this is a bug in `WebView2`.

**Comment by amaitland** [comment]
Using the [WebResourceResponseReceived Event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourceresponsereceived?view=webview2-dotnet-1.0.818.41) to look at the response header collection and it's always empty for a deferred request (at least from what I can tell).

If I load say google.com I can see the response headers for the redirect as a moved permanently to www.google.com, then there's the https upgrade request.

When I look in `DevTools` there are no response headers for a deferred request.

So it's possible I've made a mistake and generating the response header string incorrectly or there's a bug in `WebView2`.

**Comment by amaitland** [comment]
> So it's possible I've made a mistake and generating the response header string incorrectly

Would appear that this is infract the case. Should be `:` instead of `=` which is totally my mistake.

**Comment by amaitland** [comment]
@mattkol Redirects working as expected now?

**Comment by amaitland** [comment]
Thanks for the feedback, I'll push a nuget package when I get a chance 👍

**Comment by amaitland** [comment]
The first Nuget package is now available at https://www.nuget.org/packages/Chromium.AspNetCore.Bridge/
