### ISSUE TITLE
Query string starts with question mark

### ISSUE THREAD

**Issue by mattkol** [amaitland/Chromium.AspNetCore.Bridge#7]
@amaitland 

The query string from the interceptor retains question mark query marker.

https://cefsharp.test/Movies?MovieGenre=&SearchString=ghost 
decomposed to:

![image](https://user-images.githubusercontent.com/18384207/120876217-83ef1600-c57d-11eb-8b62-0f61d04b51fe.png)

This is from:
https://github.com/amaitland/Chromium.AspNetCore.Bridge/blob/50e60b41c9855d7eefedef538f1d76823610f7d9/Chromium.AspNetCore.Bridge/RequestInterceptor.cs#L63

This works:
````c#
 {"owin.RequestQueryString", uri.Query?.Trim().TrimStart('?')},
````

**Comment by amaitland** [comment]
>  owin.RequestQueryString | A string containing the query string component of the HTTP request URI, without the leading "?"  The value may be an empty string.

http://owin.org/html/spec/owin-1.0.html

Confirming the leading '?' should be trimmed as per the `OWIN` spec.

The odd part is that [IHttpRequestFeature.QueryString](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.ihttprequestfeature.querystring?view=aspnetcore-5.0) says there should be a leading `?`.

https://github.com/amaitland/Chromium.AspNetCore.Bridge/blob/master/Chromium.AspNetCore.Bridge/OwinFeatureImpl.cs#L89

Code was originally based on https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/Owin/src/OwinFeatureCollection.cs#L111

>  {"owin.RequestQueryString", uri.Query?.Trim().TrimStart('?')},

Do we need the overhead of `Trim()` and `TrimStart()`? Do we need more than a null check, maybe a length check and a `SubString(1)`?

**Comment by amaitland** [comment]
I'm wondering if we change [AddQuestionMark](https://github.com/amaitland/Chromium.AspNetCore.Bridge/blob/master/Chromium.AspNetCore.Bridge/OwinFeatureImpl.cs#L241) to 'AddQuestionMarkIfRequired` and append one if required, I suspect currently it's `??MovieGenre`.

Conforming strictly to the `OWIN` spec doesn't make much sense here at least from a performance point of view, remove the question mark, only to add one pretty much straight aware, happy to have a contrary opinion.

**Comment by amaitland** [comment]
> Conforming strictly to the `OWIN` spec doesn't make much sense here at least from a performance point of view

Quick look and it may actually be slightly more performant, there are potentially a many calls to `IHttpRequestFeature.QueryString` the `string.IsNullorEmpty` check in combination with the `queryString[0] == '?'` check would probably be fractionally more expensive.
